
OCAMLBEST   = opt
BIGINTLIB   = zarith
MPFRLIB     = 
INFERLIB    = 
INCLUDE     = -I /home/chab/lambdapi/_opam/lib/zarith -I "/home/chab/lambdapi/_opam/lib/why3"
INCLUDEALL  = -I /home/chab/lambdapi/_opam/lib/zarith  -I /home/chab/lambdapi/_opam/lib/menhirLib -I "/home/chab/lambdapi/_opam/lib/why3"


BINDIR      = "/home/chab/lambdapi/_opam/bin"
LIBDIR      = "/home/chab/lambdapi/_opam/lib/why3"
DATADIR     = "/home/chab/lambdapi/_opam/share/why3"

